services:
  - name: huffman-backend
    type: web
    env: docker
    dockerfilePath: ./Dockerfile # Path to your Dockerfile in the root
    plan: free
    autoDeploy: true
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk

  - name: huffman-frontend
    type: web
    env: static
    staticPublishPath: front-end/build # Path to your frontend build folder
    buildCommand: npm install && npm run build
    plan: free
