services:
  - name: huffman-backend
    type: web
    env: docker
    dockerfilePath: ./Dockerfile 
    plan: free
    autoDeploy: true
    buildCommand: docker build -t huffman-backend .
    startCommand: docker run -p 8080:8080 huffman-backend
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk

  - name: huffman-frontend
    type: web
    env: static
    staticPublishPath: front-end/build 
    buildCommand: npm install && npm run build
    plan: free
